### PR TITLE
Fix Nette/Utils 2.5 compatibility

### PR DESCRIPTION
**Pull request by underdpt**
This fixes Nette/Utils 2.5 warning on version 1.3.

It's done on 1.3 tag.

### CODE REVIEW

**Comment by h4kuna** [comment]
Did you try update on v2.0? Next week i will look at this PR

**Comment by underdpt** [comment]
Yeah, I tried but I was't able to fully adapt my code in time, so I did this quick fix and a pull request if someone has the same problem.

**Comment by h4kuna** [comment]
Released version 1.4.0 where is removed dependency on old php because nette/utils 2.4+ reqire php 5.6+
here is a commit d550b351d17f2c32c76e700f7742f345902554f4

**Comment by underdpt** [comment]
Thanks!

**Pull request closed without merging**
